// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzJgZepYScuXJIDuOXEd2hWxONcc8V4WU',
    appId: '1:993129977970:web:c9979085bba791881c8aeb',
    messagingSenderId: '993129977970',
    projectId: 'chatgpt-e2454',
    authDomain: 'chatgpt-e2454.firebaseapp.com',
    storageBucket: 'chatgpt-e2454.appspot.com',
    measurementId: 'G-ES3X8RSN0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA156YVOhkomRukipPe80WohhAYTkIHyK4',
    appId: '1:993129977970:android:d1ccbbb977a1452e1c8aeb',
    messagingSenderId: '993129977970',
    projectId: 'chatgpt-e2454',
    storageBucket: 'chatgpt-e2454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL-oGjR8j-MhsSyXMj2ibfH8_m-C9_I7M',
    appId: '1:993129977970:ios:e16b611a353a087f1c8aeb',
    messagingSenderId: '993129977970',
    projectId: 'chatgpt-e2454',
    storageBucket: 'chatgpt-e2454.appspot.com',
    iosBundleId: 'com.example.chatGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL-oGjR8j-MhsSyXMj2ibfH8_m-C9_I7M',
    appId: '1:993129977970:ios:8ec1c805915bfe7e1c8aeb',
    messagingSenderId: '993129977970',
    projectId: 'chatgpt-e2454',
    storageBucket: 'chatgpt-e2454.appspot.com',
    iosBundleId: 'com.example.chatGpt.RunnerTests',
  );
}
